name: Generate Konectas Source
on:
  push:
    branches:
      - main
jobs:
  build:
    if: "${{ ! contains(github.event.head_commit.message, ':robot: HTML files generated') }}"
    name: Generate Konectas Source
    runs-on: ubuntu-latest
    steps:
      - name: Configure NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: npm install
      - run: npm run generate
      - run: |
          git config user.name ${{secrets.USER_NAME}}
          git config user.email ${{secrets.USER_EMAIL}}
          git add .
          git commit -m ":robot: HTML files generated"
          git push
